name: build
on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Downcase repo
        run: echo REPOSITORY=matusnovak/prometheus-smartctl >> $GITHUB_ENV

      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          # images: ${{ env.REPOSITORY }},ghcr.io/${{ env.REPOSITORY }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=sha
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
